# Fichier de configuration
folder:
  output: '../output/'
  classifier: '../output/classifier/'
  data: 'data/'

classifier:
  Perceptron:
    train: 10000
    plot_error: True
  MultilayerPerceptron:
    train: 1000
    plot_error: True
